# Generated by Django 5.2.1 on 2025-05-26 12:41

import myApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to='uploads/', validators=[myApp.models.validate_excel_file])),
                ('date1', models.DateField()),
                ('file2', models.FileField(upload_to='uploads/', validators=[myApp.models.validate_excel_file])),
                ('date2', models.DateField()),
            ],
        ),
    ]
