# Generated by Django 5.2.1 on 2025-05-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='output',
            field=models.FileField(blank=True, null=True, upload_to='outputs/'),
        ),
    ]
