# Generated by Django 5.2.1 on 2025-06-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_fileupload_output'),
    ]

    operations = [
    ]
