# Generated by Django 5.2.1 on 2025-06-29 02:42

import django.utils.timezone
import myApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20250603_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ['-created_at'], 'verbose_name': 'File Upload', 'verbose_name_plural': 'File Uploads'},
        ),
        migrations.AddField(
            model_name='fileupload',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='date1',
            field=models.DateField(verbose_name='KW(X) Date'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='date2',
            field=models.DateField(verbose_name='KW(X-N) Date'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file1',
            field=models.FileField(upload_to='uploads/', validators=[myApp.models.validate_excel_file], verbose_name='BOOM(X) File'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file2',
            field=models.FileField(upload_to='uploads/', validators=[myApp.models.validate_excel_file], verbose_name='BOOM(X-N) File'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='output',
            field=models.FileField(blank=True, null=True, upload_to='outputs/', verbose_name='Comparison Output'),
        ),
    ]
