# Generated by Django 5.2.1 on 2025-06-29 20:26

import myApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_fileupload_options_fileupload_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={},
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='date1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='date2',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file1',
            field=models.FileField(upload_to='uploads/', validators=[myApp.models.validate_excel_file]),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file2',
            field=models.FileField(upload_to='uploads/', validators=[myApp.models.validate_excel_file]),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='output',
            field=models.FileField(blank=True, null=True, upload_to='outputs/'),
        ),
    ]
